name: PHP Composer

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Deps
      run: npm ci
    - name: Build Vue
      run: npm run build
    - name: Prepare env file for test
      run: cp .env.example .env && php artisan key:generate
    - uses: php-actions/phpunit@v3
